### ISSUE TITLE
Missing Repository URL properties

### ISSUE THREAD

**Issue by gokgozf** [mathisdt/locationstore#1]
POM is refering the missing URL properties

	<distributionManagement>
		<repository>
			<id>releases</id>
			<name>Internal Release Repository</name>
			<url>${repository_release_url}</url>
		</repository>

		<snapshotRepository>
			<id>snapshots</id>
			<name>Internal snapshot Repository</name>
			<url>${repository_snapshot_url}</url>
		</snapshotRepository>
	</distributionManagement>

Best
Fahrettin

**Comment by mathisdt** [comment]
This is intended because the target artifact repository should only be written by Jenkins. The build server creates snapshots and releases and puts them into the repo, developers don't. For this reason the variables are only contained in the settings.xml used by Jenkins, developers don't need them.
